some.age: 38

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentDB?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Root_1234

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  
        
pagesize:
    value:3    
       