some.age: 38
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Root_1234

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 
        
logging:
  level:
    ROOT: INFO
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG  
       